Repository IntelPython/numba-dpex, pull requests merged in 2020-12, with the labels that each got.

#44 Update to new API of dpCtl 0.4.0 related to USM
  conda-recipe/meta.yaml
  numba_dppy/compiler.py
  setup.py
Labels: 3 - Waiting: reviewer

#45 Delete old backup file
  numba_dppy/parfor_loop_invariant_hoisting.py.bkp
Labels: 4 - Ready to merge

#43 Del dppl dir in tests
  numba_dppy/tests/__init__.py
  numba_dppy/tests/dppl/__init__.py
  numba_dppy/tests/test_arg_accessor.py
  numba_dppy/tests/test_arg_types.py
  numba_dppy/tests/test_atomic_op.py
  numba_dppy/tests/test_barrier.py
  numba_dppy/tests/test_black_scholes.py
  numba_dppy/tests/test_caching.py
  numba_dppy/tests/test_device_array_args.py
  numba_dppy/tests/test_dpctl_api.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_dppl_fallback.py
  numba_dppy/tests/test_dppl_func.py
  numba_dppy/tests/test_math_functions.py
  numba_dppy/tests/test_numpy_bit_twiddling_functions.py
  numba_dppy/tests/test_numpy_comparison_functions.py
  numba_dppy/tests/test_numpy_floating_functions.py
  numba_dppy/tests/test_numpy_math_functions.py
  numba_dppy/tests/test_numpy_trigonomteric_functions.py
  numba_dppy/tests/test_parfor_lower_message.py
  numba_dppy/tests/test_prange.py
  numba_dppy/tests/test_print.py
  numba_dppy/tests/test_sum_reduction.py
  numba_dppy/tests/test_vectorize.py
  numba_dppy/tests/test_with_context.py
Labels: 3 - Waiting: CI

#51 Remove cffi
  conda-recipe/meta.yaml
  numba_dppy/dppl_lowerer.py
  setup.py
Labels: 3 - Waiting: CI

#42 Rename dppl to dppy
  .gitignore
  HowTo.rst
  numba_dppy/CHANGE_LOG
  numba_dppy/__init__.py
  numba_dppy/compiler.py
  numba_dppy/decorators.py
  numba_dppy/descriptor.py
  numba_dppy/dispatcher.py
  numba_dppy/dppy_host_fn_call_gen.py
  numba_dppy/dppy_lowerer.py
  numba_dppy/dppy_offload_dispatcher.py
  numba_dppy/dppy_passbuilder.py
  numba_dppy/dppy_passes.py
  numba_dppy/examples/dppy_func.py
  numba_dppy/examples/dppy_with_context.py
  numba_dppy/examples/matmul.py
  numba_dppy/examples/pairwise_distance.py
  numba_dppy/examples/sum-hybrid.py
  numba_dppy/examples/sum.py
  numba_dppy/examples/sum2D.py
  numba_dppy/examples/sum_ndarray.py
  numba_dppy/examples/sum_reduction.py
  numba_dppy/examples/sum_reduction_ocl.py
  numba_dppy/examples/sum_reduction_recursive_ocl.py
  numba_dppy/experimental_numpy_lowering_overload.py
  numba_dppy/initialize.py
  numba_dppy/ocl/atomics/atomic_ops.cl
  numba_dppy/ocl/ocldecl.py
  numba_dppy/ocl/oclimpl.py
  numba_dppy/ocl/stubs.py
  numba_dppy/printimpl.py
  numba_dppy/target.py
  numba_dppy/target_dispatcher.py
  numba_dppy/testing.py
  numba_dppy/tests/__init__.py
  numba_dppy/tests/test_arg_accessor.py
  numba_dppy/tests/test_arg_types.py
  numba_dppy/tests/test_atomic_op.py
  numba_dppy/tests/test_barrier.py
  numba_dppy/tests/test_black_scholes.py
  numba_dppy/tests/test_caching.py
  numba_dppy/tests/test_device_array_args.py
  numba_dppy/tests/test_dpctl_api.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_dppl_fallback.py
  numba_dppy/tests/test_dppl_func.py
  numba_dppy/tests/test_math_functions.py
  numba_dppy/tests/test_numpy_bit_twiddling_functions.py
  numba_dppy/tests/test_numpy_comparison_functions.py
  numba_dppy/tests/test_numpy_floating_functions.py
  numba_dppy/tests/test_numpy_math_functions.py
  numba_dppy/tests/test_numpy_trigonomteric_functions.py
  numba_dppy/tests/test_parfor_lower_message.py
  numba_dppy/tests/test_prange.py
  numba_dppy/tests/test_print.py
  numba_dppy/tests/test_sum_reduction.py
  numba_dppy/tests/test_vectorize.py
  numba_dppy/tests/test_with_context.py
Labels: 4 - Ready to merge

#46 All Numba-dppy tests and examples using the @njit decorator should be used with "with_context"
  numba_dppy/dppy_host_fn_call_gen.py
  numba_dppy/examples/pa_examples/test1-2d.py
  numba_dppy/examples/pa_examples/test1-3d.py
  numba_dppy/examples/pa_examples/test1-4d.py
  numba_dppy/examples/pa_examples/test1-5d.py
  numba_dppy/examples/pa_examples/test1.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_dppl_fallback.py
  numba_dppy/tests/test_numpy_bit_twiddling_functions.py
  numba_dppy/tests/test_numpy_comparison_functions.py
  numba_dppy/tests/test_numpy_floating_functions.py
  numba_dppy/tests/test_numpy_math_functions.py
  numba_dppy/tests/test_numpy_trigonomteric_functions.py
  numba_dppy/tests/test_parfor_lower_message.py
  numba_dppy/tests/test_prange.py
  numba_dppy/tests/test_vectorize.py
  numba_dppy/tests/test_with_context.py
Labels: 3 - Waiting: CI, 3 - Waiting: reviewer

#57 To update all the tests in numba_dppy/tests/dppl
  numba_dppy/testing.py
  numba_dppy/tests/test_arg_accessor.py
  numba_dppy/tests/test_arg_types.py
  numba_dppy/tests/test_atomic_op.py
  numba_dppy/tests/test_barrier.py
  numba_dppy/tests/test_black_scholes.py
  numba_dppy/tests/test_caching.py
  numba_dppy/tests/test_device_array_args.py
  numba_dppy/tests/test_dpctl_api.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_dppl_fallback.py
  numba_dppy/tests/test_dppl_func.py
  numba_dppy/tests/test_math_functions.py
  numba_dppy/tests/test_numpy_bit_twiddling_functions.py
  numba_dppy/tests/test_numpy_comparison_functions.py
  numba_dppy/tests/test_numpy_floating_functions.py
  numba_dppy/tests/test_numpy_math_functions.py
  numba_dppy/tests/test_numpy_trigonomteric_functions.py
  numba_dppy/tests/test_parfor_lower_message.py
  numba_dppy/tests/test_prange.py
  numba_dppy/tests/test_print.py
  numba_dppy/tests/test_rename_numpy_function_pass.py
  numba_dppy/tests/test_sum_reduction.py
  numba_dppy/tests/test_vectorize.py
  numba_dppy/tests/test_with_context.py
Labels: 3 - Waiting: CI, 3 - Waiting: reviewer

#27 Add flags to generate debug symbols
  DEBUGGING.md
  README.md
  numba_dppy/compiler.py
  numba_dppy/target.py
Labels: 3 - Waiting: CI, 4 - Ready to merge, enhancement

#40 Controllable fallback
  numba_dppy/config.py
  numba_dppy/dppy_lowerer.py
  numba_dppy/tests/test_controllable_fallback.py
Labels: 4 - Ready to merge

#68 Fix fallback test
  numba_dppy/tests/test_controllable_fallback.py
Labels: 3 - Waiting: CI, 4 - Ready to merge

#79 Update how we load dpctl library
  numba_dppy/initialize.py
Labels: 3 - Waiting: reviewer

#61 Implementation of np.linalg.eig
  numba_dppy/dpnp_glue/dpnp_linalgimpl.py
  numba_dppy/dpnp_glue/dpnp_transcendentalsimpl.py
  numba_dppy/dpnp_glue/dpnpimpl.py
  numba_dppy/dpnp_glue/stubs.py
  numba_dppy/rename_numpy_functions_pass.py
  numba_dppy/tests/test_dpnp_functions.py
Labels: 2 - Ready for Review

#118 Spokhode/dparray tests
  numba_dppy/tests/test_usmarray.py
Labels: tests

#29 Offload diagnostics
  numba_dppy/compiler.py
  numba_dppy/config.py
  numba_dppy/dppy_lowerer.py
  numba_dppy/dppy_parfor_diagnostics.py
  numba_dppy/dppy_passbuilder.py
  numba_dppy/dppy_passes.py
  numba_dppy/tests/test_offload_diagnostics.py
  numba_dppy/tests/test_prange.py
Labels: 4 - Ready to merge

#114 Extended docs for debugger
  DEBUGGING.md
Labels: 2 - Ready for Review

#63 Rewrite supported ndarray.function_name
  numba_dppy/dpnp_glue/dpnp_transcendentalsimpl.py
  numba_dppy/dppy_passbuilder.py
  numba_dppy/rename_numpy_functions_pass.py
  numba_dppy/testing.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_numpy_math_functions.py
  numba_dppy/tests/test_rename_numpy_function_pass.py
Labels: 3 - Waiting: CI, 3 - Waiting: author

#115 Port existing functions enabled through dpnp
  numba_dppy/dpnp_glue/__init__.py
  numba_dppy/dpnp_glue/dpnp_linalgimpl.py
  numba_dppy/dpnp_glue/dpnp_sort_search_countimpl.py
  numba_dppy/dpnp_glue/dpnp_statisticsimpl.py
  numba_dppy/dpnp_glue/dpnp_transcendentalsimpl.py
  numba_dppy/dpnp_glue/dpnpdecl.py
  numba_dppy/dpnp_glue/dpnpimpl.py
  numba_dppy/dpnp_glue/stubs.py
  numba_dppy/dppy_passbuilder.py
  numba_dppy/dppy_passes.py
  numba_dppy/experimental_numpy_lowering_overload.py
  numba_dppy/rename_numpy_functions_pass.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_dppy_fallback.py
Labels: 4 - Ready to merge

#124 Add scipy to dependency to README.md
  README.md
Labels: documentation

#113 Added docs for Offload Diagnostics and Controllable Fallback
  README.md
  docs/INDEX.md
Labels: documentation

#126 update CHANGELOG
  CHANGELOG.md
  numba_dppy/CHANGE_LOG
Labels: 3 - Waiting: reviewer, documentation

#120 Skip tests
  numba_dppy/tests/skip_tests.py
  numba_dppy/tests/test_numpy_math_functions.py
  numba_dppy/tests/test_numpy_trigonomteric_functions.py
Labels: 3 - Waiting: author, 4 - Ready to merge
