Repository IntelPython/numba-dpex, pull requests merged in 2021-11, with the labels that each got.

#609 Improvements for automatically generated release notes
  .github/release.yml
  CHANGELOG.md
Labels: enhancement

#600 Change GDB tests for new Numba features
  numba_dppy/tests/test_debug_dppy_numba.py
Labels: 2 - Ready for Review

#621 Run coverage in GitHub Actions and upload results to coveralls.io
  .github/workflows/generate-coverage.yml
  README.md
Labels: 2 - Ready for Review, infrastructure

#626 Use llvm-spirv from bin-llvm during build
  conda-recipe/build.sh
Labels: llvm-spirv

#627 Use llvm-spirv from bin-llvm during build on Windows
  conda-recipe/bld.bat
  setup.py
Labels: llvm-spirv

#610 Fix upload conditions for main and release branches [Public CI]
  .github/workflows/conda-package.yml
  CHANGELOG.md
Labels: bug, infrastructure

#643 Pin numba 0.55 package for testing
  .github/workflows/conda-package.yml
Labels: bug, infrastructure

#647 Convert unittest to pytest
  numba_dppy/tests/_helper.py
  numba_dppy/tests/passes/test_rename_numpy_function_pass.py
  numba_dppy/tests/test_black_scholes.py
  numba_dppy/tests/test_controllable_fallback.py
  numba_dppy/tests/test_device_array_args.py
  numba_dppy/tests/test_dpnp_functions.py
  numba_dppy/tests/test_dppy_fallback.py
  numba_dppy/tests/test_dppy_func.py
  numba_dppy/tests/test_offload_diagnostics.py
  numba_dppy/tests/test_parfor_lower_message.py
  numba_dppy/tests/test_prange.py
  numba_dppy/tests/test_sum_reduction.py
  numba_dppy/tests/test_usmarray.py
  numba_dppy/tests/test_with_context.py
Labels: tests

#649 Use `llvm-spirv` from `dpcpp` compiler package by default
  conda-recipe/meta.yaml
  conda-recipe/run_test.sh
  numba_dppy/config.py
  numba_dppy/spirv_generator.py
Labels: llvm-spirv, feature-change
