Repository IntelPython/numba-dpex, pull requests merged in 2021-02, with the labels that each got.

#220 Add wheels build + Update linux build tag for wheels
  conda-recipe/bld.bat
  conda-recipe/build.sh
  conda-recipe/meta.yaml
Labels: 4 - Ready to merge

#238 Unskip rng tests
  numba_dppy/tests/test_dpnp_functions.py
Labels: 2 - Ready for Review, 3 - Waiting: CI, tests

#243 Fix rng tests
  numba_dppy/tests/test_dpnp_functions.py
Labels: 4 - Ready to merge

#258 Implement np.cumsum and np.cumprod in kernel by dpnp
  numba_dppy/dpnp_glue/dpnp_array_ops_impl.py
  numba_dppy/dpnp_glue/dpnp_fptr_interface.pyx
  numba_dppy/dpnp_glue/stubs.py
  numba_dppy/rename_numpy_functions_pass.py
  numba_dppy/tests/test_dpnp_functions.py
Labels: 3 - Waiting: CI

#246 Implement np.take in kernel by dpnp
  numba_dppy/dpnp_glue/dpnp_array_ops_impl.py
  numba_dppy/dpnp_glue/dpnp_fptr_interface.pyx
  numba_dppy/dpnp_glue/stubs.py
  numba_dppy/rename_numpy_functions_pass.py
  numba_dppy/tests/test_dpnp_functions.py
Labels: 3 - Waiting: reviewer

#136 Fix incorrect import in examples
  numba_dppy/examples/pairwise_distance.py
  numba_dppy/examples/sum_reduction_recursive_ocl.py
Labels: 3 - Waiting: reviewer
