Repository IntelPython/numba-dpex, pull requests merged in 2021-01, with the labels that each got.

#50 Add support for dpctl.dparray.
  README.md
  conda-recipe/meta.yaml
  numba_dppy/dppy_rt.c
  numba_dppy/numpy_usm_shared.py
  numba_dppy/tests/test_usmarray.py
  setup.py
Labels: 3 - Waiting: author

#187 Extend docs for Debugging
  README.md
  docs/DEBUGGING.md
  docs/dppy/debugging.md
  docs/dppy/index.rst
  docs/index.rst
Labels: 2 - Ready for Review

#191 Doc for writing kernels
  docs/dppy/index.rst
  docs/dppy/writing_kernels.rst
Labels: 1 - In Progress

#141 Numpy.random implementations
  numba_dppy/dpnp_glue/__init__.py
  numba_dppy/dpnp_glue/dpnp_fptr_interface.pyx
  numba_dppy/dpnp_glue/dpnp_randomimpl.py
  numba_dppy/dpnp_glue/dpnpdecl.py
  numba_dppy/dpnp_glue/dpnpimpl.py
  numba_dppy/dpnp_glue/stubs.py
  numba_dppy/rename_numpy_functions_pass.py
  numba_dppy/testing.py
  numba_dppy/tests/test_dpnp_functions.py
Labels: 4 - Ready to merge

#175 Add wheels build + Update linux build tah for wheels
  conda-recipe/bld.bat
  conda-recipe/build.sh
  conda-recipe/meta.yaml
Labels: 4 - Ready to merge

#131 Move spirv
  conda-recipe/bld.bat
  conda-recipe/build.sh
  setup.py
Labels: build, infrastructure
