Repository IntelPython/numba-dpex, pull requests merged in 2021-07, with the labels that each got.

#491 reviewed features.rst
  docs/user_guides/debugging/features.rst
Labels: debug, documentation

#494 update CHANGELOG 0.14.4
  CHANGELOG.md
Labels: 2 - Ready for Review, documentation

#500 Pass required compiler flags for processing genreated DWARF symbols
  numba_dppy/compiler.py
Labels: bug, debug

#502 Use dpcpp compiler package for Linux
  conda-recipe/build.sh
  conda-recipe/meta.yaml
  setup.py
Labels: build, infrastructure

#505 Add `packaging` in run dependencies
  README.md
  conda-recipe/meta.yaml
  docs/user_guides/getting_started.rst
  setup.py
Labels: bug, build

#498 Remove `llvmdev` from runtime dependecies
  conda-recipe/meta.yaml
Labels: build, infrastructure

#508 Skip tests for run without GPU
  numba_dppy/tests/integration/test_dpnp_interop.py
  numba_dppy/tests/integration/test_usm_ndarray_interop.py
  numba_dppy/tests/test_array_utils.py
  numba_dppy/tests/test_strided_array.py
Labels: bug, tests

#497 Enable @vectorize for target dppy
  numba_dppy/dpnp_glue/dpnp_array_creations_impl.py
  numba_dppy/examples/vectorize.py
  numba_dppy/initialize.py
  numba_dppy/tests/test_vectorize.py
  numba_dppy/vectorizers.py
Labels: enhancement
