Repository IntelPython/numba-dpex, pull requests merged in 2022-02, with the labels that each got.

#707 Load dpctl lib on Linux using `libDPCTLSyclInterface.so.0`
  numba_dppy/initialize.py
Labels: bug, dpctl

#703 Fix search llvm-spirv if dpcpp compiler package is not installed
  numba_dppy/spirv_generator.py
Labels: bug, llvm-spirv

#708 Support for coverage in internal CI
  conda-recipe/meta.yaml
Labels: infrastructure
